import pandas as pd


COMMON_LABEL_VALUES = {
    "A": "1.25",
    "B": "3.10",
    "C": "2.40",
    "D": "1.80",
    "E": "2.70",
    "F": "3.20",
    "G": "1.60",
    "H": "2.15",
    "I": "4.25",
    "J": "3.75",
    "K": "2.95",
    "L": "3.35",
    "M": "2.05",
    "N": "1.90",
    "O": "2.60",
    "P": "3.45",
    "Q": "2.35",
    "R": "4.10",
    "S": "1.70",
    "T": "2.20",
    "U": "3.65",
    "V": "1.55",
    "W": "2.85",
    "X": "3.95",
    "Y": "2.50",
    "Z": "1.40",
    "AA": "2.75",
}


DEMO_ROWS = {
    "demo1": {
        **COMMON_LABEL_VALUES,
        "Drawing": "Drawing1",
        "FileName": "GNT_DEMO_LAYOUT_001",
        "Type": "DN_MAIN",
        "SECTION": "GUNTUR - TENALI",
        "LAYOUT No": "GNT/LE/001",
        "CHAINAGE": "KM 03/420",
        "WIND PRESSURE": "150 kg/m2",
        "LOCATION No.": "GNT-101",
        "MAST TYPE": "B-200",
        "MAST LENGTH": "9.5 m",
        "REV.DEF.IN mm": "42",
        "NATURE OF SOIL": "Black cotton",
        "SOIL PRESSURE": "16 T/m2",
        "FOUNDATION REF.": "F-01",
        "ANCHOR BLOCK": "AB-12",
        "SUPER MAST": "No",
        "RC/FEEDER HT. (m)": "7.20",
        "CATENARY HT. (m)": "6.75",
        "CONTACT HT. (m)": "5.65",
        "SPAN (m)": "63",
        "VERSINES / RADIUS": "R 875",
        "SUPER ELEVATION": "75 mm",
        "STAY INSULATOR ": "2026",
        "BKT . INSULATOR": "2026",
        "9 - TONNE INSULATOR ": "2025",
        "S.S WIRE ROPE": "8 mm",
        "CONTACT WIRE": "107 sq mm",
        "CATENARY WIRE": "65 sq mm",
    },
    "demo2": {
        **COMMON_LABEL_VALUES,
        "Drawing": "Drawing2",
        "FileName": "TEL_DEMO_LAYOUT_014",
        "Type": "UP_MAIN",
        "SECTION": "TENALI YARD",
        "LAYOUT No": "TEL/LE/014",
        "CHAINAGE": "KM 14/860",
        "WIND PRESSURE": "160 kg/m2",
        "LOCATION No.": "TEL-214",
        "MAST TYPE": "SPS-250",
        "MAST LENGTH": "10.0 m",
        "REV.DEF.IN mm": "55",
        "NATURE OF SOIL": "Sandy clay",
        "SOIL PRESSURE": "18 T/m2",
        "FOUNDATION REF.": "F-03",
        "ANCHOR BLOCK": "AB-18",
        "SUPER MAST": "Yes",
        "RC/FEEDER HT. (m)": "7.45",
        "CATENARY HT. (m)": "6.95",
        "CONTACT HT. (m)": "5.75",
        "SPAN (m)": "58",
        "VERSINES / RADIUS": "R 720",
        "SUPER ELEVATION": "90 mm",
        "STAY INSULATOR ": "2026",
        "BKT . INSULATOR": "2025",
        "9 - TONNE INSULATOR ": "2026",
        "S.S WIRE ROPE": "10 mm",
        "CONTACT WIRE": "107 sq mm",
        "CATENARY WIRE": "65 sq mm",
    },
    "demo3": {
        **COMMON_LABEL_VALUES,
        "Drawing": "Drawing3",
        "FileName": "BZA_DEMO_LAYOUT_028",
        "Type": "LOOP_LINE",
        "SECTION": "BRIDGE APPROACH",
        "LAYOUT No": "BZA/LE/028",
        "CHAINAGE": "KM 22/175",
        "WIND PRESSURE": "145 kg/m2",
        "LOCATION No.": "BZA-328",
        "MAST TYPE": "K-175",
        "MAST LENGTH": "9.0 m",
        "REV.DEF.IN mm": "36",
        "NATURE OF SOIL": "Rocky strata",
        "SOIL PRESSURE": "22 T/m2",
        "FOUNDATION REF.": "F-07",
        "ANCHOR BLOCK": "AB-24",
        "SUPER MAST": "No",
        "RC/FEEDER HT. (m)": "7.10",
        "CATENARY HT. (m)": "6.60",
        "CONTACT HT. (m)": "5.55",
        "SPAN (m)": "49",
        "VERSINES / RADIUS": "Straight",
        "SUPER ELEVATION": "0 mm",
        "STAY INSULATOR ": "2025",
        "BKT . INSULATOR": "2026",
        "9 - TONNE INSULATOR ": "2026",
        "S.S WIRE ROPE": "8 mm",
        "CONTACT WIRE": "107 sq mm",
        "CATENARY WIRE": "65 sq mm",
    },
}


def get_demo_dataframe(username: str) -> pd.DataFrame:
    row = DEMO_ROWS.get(username)
    if row is None:
        raise ValueError(f"No demo data configured for user: {username}")
    return pd.DataFrame([row])
